dev_ca: &dev_ca
  client_ca_key: "./test/files/ca.key"
  client_ca_cert: "./test/files/ca.crt"
  ca_key_password: nil

cert_options: &cert_options
  client_cert_lifespan: 2
  client_cert_bit_size: 2024
  client_cert_hash: "SHA256"
  allow_limited_certs: false
  allow_unlimited_certs: true
  allow_anonymous_certs: false
  limited_cert_prefix: "LIMITED"
  unlimited_cert_prefix: "UNLIMITED"

downloads: &downloads
  client_download_domain: https://dl.bitmask.net
  available_clients:
    - linux
    - osx
    - windows
    - android
  download_paths:
    android: /android/
    linux:   /linux/
    osx:     /mac/
    windows: /windows/
    other:   /

common: &common
  force_ssl: false
  pagination_size: 30
  auth:
    token_expires_after: 60
  # handles that will be blocked from being used as logins or email aliases
  # in addition to the ones in /etc/passwd and http://tools.ietf.org/html/rfc2142
  handle_blacklist: ['certmaster', 'ssladmin', 'arin-admin', 'administrator', 'www-data', 'maildrop', 'postmaster', 'admin', 'contact', 'info']
  # handles that will be allowed despite being in /etc/passwd or rfc2142
  handle_whitelist: []
  # actions enabled in the account settings
  # see /users/app/views/users/_edit.html.haml for a list.
  user_actions: ['destroy_account']
  admin_actions: ['change_pgp_key', 'change_service_level', 'destroy_account']
  billing: ~
  default_locale: :en
  available_locales:
    - :en
  minimum_client_version: "0.5"
  engines:
    - support
    - billing

service_levels: &service_levels
  service_levels:
    1:
      name: free
      description: "free account, with rate limited VPN"
      eip_rate_limit: true
      storage: 100
      services:
        - eip
    2:
      name: premium
      description: "premium account, with unlimited vpn"
      rate:
        USD: 10
        EUR: 10
      services:
        - eip
        - email
  default_service_level: 1

development:
  <<: *downloads
  <<: *dev_ca
  <<: *cert_options
  <<: *common
  <<: *service_levels
  admins: [blue, admin, admin2]
  domain: example.org
  secret_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  reraise_errors: true

test:
  <<: *downloads
  <<: *dev_ca
  <<: *cert_options
  <<: *common
  <<: *service_levels
  admins: [admin, admin2]
  domain: test.me
  secret_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  reraise_errors: true
  billing: {}
  default_locale: :en
  available_locales:
    - :en
    - :de

production:
  <<: *downloads
  <<: *cert_options
  <<: *common
  admins: []
  domain: example.net
  # logfile: /path/to/your/logs
